version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/akb"
      REDIS_URI: "redis://redis:6379/0"

volumes:
  mongodb_data:
  redis_data:
